// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project configuration
  // Run: flutterfire configure --project=your-firebase-project-id
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'AIzaSyGraduWayWebApiKeyPlaceholder'),
    appId: '1:123456789:web:graduway-placeholder',
    messagingSenderId: '123456789',
    projectId: 'graduway-aditya-college',
    authDomain: 'graduway-aditya-college.firebaseapp.com',
    storageBucket: 'graduway-aditya-college.firebasestorage.app',
    measurementId: 'G-GRADUWAY001',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'AIzaSyGraduWayAndroidApiKeyPlaceholder'),
    appId: '1:123456789:android:graduway-android-placeholder',
    messagingSenderId: '123456789',
    projectId: 'graduway-aditya-college',
    storageBucket: 'graduway-aditya-college.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'AIzaSyGraduWayIosApiKeyPlaceholder'),
    appId: '1:123456789:ios:graduway-ios-placeholder',
    messagingSenderId: '123456789',
    projectId: 'graduway-aditya-college',
    storageBucket: 'graduway-aditya-college.firebasestorage.app',
    iosBundleId: 'com.adityacollege.graduway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: 'AIzaSyGraduWayMacosApiKeyPlaceholder'),
    appId: '1:123456789:ios:graduway-macos-placeholder',
    messagingSenderId: '123456789',
    projectId: 'graduway-aditya-college',
    storageBucket: 'graduway-aditya-college.firebasestorage.app',
    iosBundleId: 'com.adityacollege.graduway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: 'AIzaSyGraduWayWindowsApiKeyPlaceholder'),
    appId: '1:123456789:web:graduway-windows-placeholder',
    messagingSenderId: '123456789',
    projectId: 'graduway-aditya-college',
    authDomain: 'graduway-aditya-college.firebaseapp.com',
    storageBucket: 'graduway-aditya-college.firebasestorage.app',
    measurementId: 'G-GRADUWAY001',
  );
}
